### ISSUE TITLE
Generic conv implementation only supports NHWC tensor format for now

### ISSUE THREAD

**Issue by pharrellyhy** [Vetal1977/tf_serving_example#6]
Hi,

I want to speed up the time when making tensor_proto, so I followed your sample code in `svnh_semi_supervised_client_no_tf.py`. While in this case, I got the error message specified in the title. My model is in NCHW format and can work well if input is made using `make_tensor_proto`.  Any thoughts on this situation?

**Comment by Vetal1977** [comment]
Hi,
could you please give me a full error stack? And which version of the TensorFlow do you currently have? Thank you in advance.

**Comment by pharrellyhy** [comment]
For some reason, the tf serving is not running on gpu anymore... Closing it for now...

**Comment by pharrellyhy** [comment]
I built a cc client using bazel inside the serving docker. After that, the serving cannot run on the gpu...
